dependencies:
  - "OpenZeppelin/openzeppelin-contracts@4.5.0"
  - "smartcontractkit/chainlink-brownie-contracts@0.4.0"

compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0"

networks:
    default: development
    development:
        verify: False
  
    goerli:
      verify: True
    matic:
      verify: True
    polygon-test:
      verify: True
    bsc-test:
      verify: True
   


wallets:
    from_key: ${PRIVATE_KEY}

